#!/bin/bash

# Define the color codes for different frame IDs
COLORS=(
  "\033[0;31m"   # red
  "\033[0;32m"   # green
  "\033[1;33m"   # yellow
  "\033[0;34m"   # blue
  "\033[0;35m"   # magenta
  "\033[0;36m"   # cyan
  "\033[1;31m"   # bright red
  "\033[1;32m"   # bright green
  "\033[1;33m"   # bright yellow
  "\033[1;34m"   # bright blue
  "\033[1;35m"   # bright magenta
  "\033[1;36m"   # bright cyan
)
RESET="\033[0m"

declare -A FRAME_IDS

# Loop through each line in the input file
while read -r line; do
    # Extract the CAN ID from the line
    can_id=$(echo "$line" | cut -d '#' -f 1 | awk '{print $3}')
    
    # Check if the CAN ID has already been assigned a color
    if [[ -v FRAME_IDS["$can_id"] ]]; then
        # If so, use the assigned color
        color_code="${FRAME_IDS[$can_id]}"
    else
        # If not, assign a new color
        color_code="${COLORS[${#FRAME_IDS[@]} % ${#COLORS[@]}]}"
        FRAME_IDS["$can_id"]=$color_code
    fi
    
    # Print the line with the appropriate color code
echo -e "${color_code}${line}${RESET}"
done < "$1"
